[build-system]                          # Required for `uv`
requires = ["setuptools >= 77"]
build-backend = "setuptools.build_meta"

[project]
name = "puppibuff"
version = "1.0.0"
description = "BDT-based flow matching for on-the-fly event generation on FPGA firmware"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">= 3.11"
authors = [
    { name = "Koen Waggeveld", email = "k.c.waggeveld@student.rug.nl" },
]
dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
    "xgboost >= 3.2",
    "scikit-learn",
    "joblib",
    "tqdm",
    "conifer >= 1.9",
]

[project.optional-dependencies]
scripts = [
    "vector",
    "fastjet",
    "awkward",
]

[project.urls]
Repository = "https://github.com/kwaggeveld/puppibuff"

[dependency-groups]
dev = [
    "mypy >= 2.3.1",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"puppibuff.hls" = ["firmware/*"]
"puppibuff.codecs" = ["firmware/*"]

[tool.mypy]
disable_error_code = ["import-untyped"]
