[project]
name = "puppibuff"
version = "0.0.0"
dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
    "xgboost",
    "joblib",
    "tqdm",
    "conifer >= 1.9",
]

[project.optional-dependencies]
scripts = [
    "vector",
    "fastjet",
    "awkward",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"puppibuff.hls" = ["firmware/*"]
"puppibuff.codecs" = ["firmware/*"]

[tool.mypy]
disable_error_code = ["import-untyped", "import-not-found"]